### ISSUE TITLE
Enable userspace to read the real config?

### ISSUE THREAD

**Issue by cachiusa** [dereference23/kernel_xiaomi_sm6375#3]
It would be good to revert https://github.com/dereference23/kernel_xiaomi_sm6375/commit/c138e767da9ef9a03e43b62540c49b998a902c77
Doing so will allow anyone to see what's baked inside the image, if it doesn't affect the functionality much
Can you give more detail about `spits out an error message after boot
finishes when it doesn't like the kernel's configuration` part

**Comment by dereference23** [comment]
https://community.oneplus.com/thread/1065627

**Comment by cachiusa** [comment]
That's not the case for our device. I tested a version without this commit and it didn't cause the mentioned error.
If you can confirm that, you should revert the change so users won't be confused about what actual features are present in their kernel
